export const demoTasks = [
  {
    id: "demo-1",
    title: "Escort elderly missing case to Ramkund help desk",
    description: "Find booth staff and verify family claimant before handover.",
    assigned_to: "Saaheer",
    status: "new",
    priority: "critical",
    zone_name: "Zone Area 1",
    created_at: new Date().toISOString(),
    live_case: {
      missing_person_name: null,
      age_band: "71-80",
      gender: "Female",
      language: "Maithili",
      last_seen_location: "Ramkund Ghat",
      risk_flags: ["elderly", "no_name", "needs_private_verification"],
      physical_description: "Elderly woman in green saree, tilak, confused near ghat.",
    },
  },
  {
    id: "demo-2",
    title: "Check WhatsApp child report near river",
    description: "High-risk child report. Go to nearest help point and update status.",
    assigned_to: "Saaheer",
    status: "accepted",
    priority: "critical",
    zone_name: "Zone Area 3",
    created_at: new Date().toISOString(),
    live_case: {
      missing_person_name: null,
      age_band: "0-12",
      gender: "Unknown",
      language: "English",
      last_seen_location: "river",
      risk_flags: ["child", "possible_death_or_medical_emergency"],
      physical_description: "Child reported lost near river through WhatsApp.",
    },
  },
];
